# Generated by Django 5.2 on 2025-04-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Giile Pro', max_length=100, verbose_name='Page Title')),
                ('intro', models.TextField(help_text='Introductory text at the top of the page', verbose_name='Introduction')),
                ('our_story_title', models.CharField(default='Our Story', max_length=100, verbose_name='Our Story Title')),
                ('our_story', models.TextField(verbose_name='Our Story Content')),
                ('our_story_image', models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Our Story Image')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100, verbose_name='Vision Title')),
                ('vision', models.TextField(verbose_name='Vision Content')),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Vision Image')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100, verbose_name='Mission Title')),
                ('mission', models.TextField(verbose_name='Mission Content')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/images/', verbose_name='Mission Image')),
                ('values_title', models.CharField(default='Our Values', max_length=100, verbose_name='Values Title')),
                ('team_title', models.CharField(default='Our Team', max_length=100, verbose_name='Team Title')),
                ('team_subtitle', models.TextField(blank=True, verbose_name='Team Subtitle')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Giile Pro', max_length=100, verbose_name='Site Title')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Copyright Text')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('bio', models.TextField(verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/photos/', verbose_name='Photo')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Value Title')),
                ('description', models.TextField(verbose_name='Value Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['order'],
            },
        ),
    ]
