# Generated by Django 5.2 on 2025-04-18 09:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='intro',
            field=ckeditor.fields.RichTextField(help_text='Introductory text at the top of the page', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=ckeditor.fields.RichTextField(verbose_name='Mission Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='our_story',
            field=ckeditor.fields.RichTextField(verbose_name='Our Story Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_subtitle',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Team Subtitle'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=ckeditor.fields.RichTextField(verbose_name='Vision Content'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Footer Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Site Description'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=ckeditor.fields.RichTextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Value Description'),
        ),
    ]
