# Generated by Django 5.2 on 2025-04-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aboutpage_intro_alter_aboutpage_mission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Giile Pro', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(default='Your premier entertainment management platform', max_length=200, verbose_name='Hero Subtitle')),
                ('hero_button_text', models.CharField(default='Get Started', max_length=50, verbose_name='Hero Button Text')),
                ('hero_button_url', models.CharField(default='/accounts/signup/', max_length=100, verbose_name='Hero Button URL')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/images/', verbose_name='Hero Image')),
                ('services_title', models.CharField(default='Our Services', max_length=100, verbose_name='Services Title')),
                ('events_title', models.CharField(default='Upcoming Events', max_length=100, verbose_name='Events Title')),
                ('events_button_text', models.CharField(default='View All Events', max_length=50, verbose_name='Events Button Text')),
                ('events_button_url', models.CharField(default='/events/', max_length=100, verbose_name='Events Button URL')),
                ('blog_title', models.CharField(default='Latest News', max_length=100, verbose_name='Blog Title')),
                ('blog_button_text', models.CharField(default='View All News', max_length=50, verbose_name='Blog Button Text')),
                ('blog_button_url', models.CharField(default='/blog/', max_length=100, verbose_name='Blog Button URL')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event Title')),
                ('date', models.CharField(max_length=100, verbose_name='Event Date')),
                ('location', models.CharField(max_length=100, verbose_name='Event Location')),
                ('button_text', models.CharField(default='Get Tickets', max_length=50, verbose_name='Button Text')),
                ('button_url', models.CharField(max_length=100, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('excerpt', models.TextField(verbose_name='Post Excerpt')),
                ('date', models.CharField(max_length=100, verbose_name='Post Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Post Image')),
                ('button_text', models.CharField(default='Read More', max_length=50, verbose_name='Button Text')),
                ('button_url', models.CharField(max_length=100, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Service Image')),
                ('button_text', models.CharField(default='Explore', max_length=50, verbose_name='Button Text')),
                ('button_url', models.CharField(max_length=100, verbose_name='Button URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
