# Generated by Django 5.2 on 2025-04-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aboutpage_options_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(max_length=100, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(max_length=100, verbose_name='Event Date'),
        ),
    ]
