# Generated by Django 5.2 on 2025-04-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpost_date_alter_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
