# Generated by Django 5.2 on 2025-04-19 23:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TalentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Talent Category',
                'verbose_name_plural': 'Talent Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='talents/profile/', verbose_name='Profile Image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='talents/cover/', verbose_name='Cover Image')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('short_bio', models.TextField(help_text='A brief introduction (max 200 words)', verbose_name='Short Bio')),
                ('biography', ckeditor.fields.RichTextField(blank=True, verbose_name='Biography')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('featured', 'Featured')], default='active', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('skills', models.ManyToManyField(blank=True, related_name='talents', to='talent.skill', verbose_name='Skills')),
                ('categories', models.ManyToManyField(related_name='talents', to='talent.talentcategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='talents/portfolio/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL', verbose_name='Video URL')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Project Date')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Client')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='talent.talent', verbose_name='Talent')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['order', '-project_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Client Email')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Client Phone')),
                ('client_company', models.CharField(blank=True, max_length=100, verbose_name='Client Company')),
                ('project_title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('project_description', models.TextField(verbose_name='Project Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes visible only to administrators', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='talent.talent', verbose_name='Talent')),
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('client_position', models.CharField(blank=True, max_length=100, verbose_name='Client Position')),
                ('client_company', models.CharField(blank=True, max_length=100, verbose_name='Client Company')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='talents/testimonials/', verbose_name='Client Image')),
                ('content', models.TextField(verbose_name='Testimonial Content')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Rating')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='talent.talent', verbose_name='Talent')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-date'],
            },
        ),
    ]
