# Generated by Django 5.2 on 2025-04-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='show_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_dates', to='talent.talent')),
            ],
            options={
                'verbose_name': 'Availability Date',
                'verbose_name_plural': 'Availability Dates',
                'ordering': ['date'],
                'unique_together': {('talent', 'date')},
            },
        ),
    ]
